[package]
name = "okto"
version = "1.1.1"
authors = ["CallidusU <callidusumbra@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A Discord bot for getting information about upcoming rocket launches"


[dependencies]
serenity = "0.9.3"
lazy_static = "1.4"
reqwest = { version = "^0.10.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
chrono = "0.4.19"
rand = "0.8"
bson = "1.1.0"
url = "2.2"
regex = "1"
num_cpus = "1.13"
threadpool = "1.8"
tokio = { version = "0.2", features = ["full"] }
mongodb = "1.1"
futures = "0.3"
