[package]
name = "okto"
version = "2.0.0"
authors = ["Calli <me@calli.dev>"]
edition = "2024"
license = "MIT"
description = "A Discord bot for getting information about upcoming rocket launches"

[dependencies.okto_framework]
path = "./okto_framework"
version = "0.1.0"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[dependencies]
serenity = {version="0.12.4"}
lazy_static = "1.5"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
chrono = "0.4.40"
rand = "0.8"
url = "2.5"
regex = "1.11"
num_cpus = "1.16"
threadpool = "1.8"
tokio = { version = "1.36.0", features = ["full", "tracing"] }
mongodb = "3.2"
futures = "0.3"
itertools = "0.14.0"
http = "1.2.0"
serde_regex = "1.1.0"
