imports_layout = "Vertical"
match_block_trailing_comma = true
wrap_comments = true
combine_control_expr = false
struct_lit_single_line = false
use_field_init_shorthand = true
chain_width = 0
group_imports = "StdExternalCrate"

