name: Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: rustup component add clippy
      - name: Check
        run: cargo check --verbose
      - name: Lint
        run: |
          cargo clippy -- -D warnings
          cd command_macros
          cargo clippy -- -D warnings
          cd ../okto_framework
          cargo clippy -- -D warnings
      - name: Test
        run: cargo test
