name: Check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: rustup component add clippy
      - name: Check
        run: cargo check --verbose
      - name: Lint
        run: cargo clippy -- -D warnings
